import { useState } from 'react';
import { Sparkles, RefreshCw, CheckCircle2, AlertCircle, Maximize2 } from 'lucide-react';
import type { InboxEntry } from '@shared/types';
import {
  useInboxSummary,
  refreshInboxSummary,
  inboxContentSignature
} from '../store';
import { InboxSummaryModal } from './InboxSummaryModal';

/**
 * The "AI Summary" card at the top of the Inbox list — a standup-style digest of
 * recent inbox activity (what got done · what needs attention), generated by the
 * `builtin:inbox-summary` LLM micro-call.
 *
 * Scope follows the shell: when drilled into a project (`scopeProjectId` set) it
 * summarizes that project; otherwise the whole inbox. Generation is USER-DRIVEN:
 * no automatic background refresh on mount/open. The refresh button triggers
 * generation/regeneration explicitly.
 *
 * `entries` is the already-scoped list the InboxPane holds, so the content
 * signature (add/remove/coalesce) and the digest's scope always agree.
 */
export function InboxSummaryCard({
  scopeProjectId,
  entries
}: {
  scopeProjectId: string | null;
  entries: InboxEntry[];
}) {
  const scopeKey = scopeProjectId ?? '__all__';
  const item = useInboxSummary((s) => s.byScope[scopeKey]);
  const [modalOpen, setModalOpen] = useState(false);
  const signature = inboxContentSignature(entries);

  const loading = item?.loading ?? false;
  const digest = item?.digest ?? null;
  const error = item?.error ?? null;

  // User-driven only: keep the card hidden until a summary has been explicitly
  // generated (or is currently generating, or failed after an explicit attempt).
  if (!digest && !loading && !error) {
    return null;
  }
  // Nothing to summarize in this scope.
  if (!digest && !loading && error === 'empty') {
    return null;
  }

  const onRefresh = () => {
    if (loading) return;
    void refreshInboxSummary(scopeProjectId, signature);
  };

  return (
    <>
      {modalOpen && (
        <InboxSummaryModal scopeProjectId={scopeProjectId} entries={entries} onClose={() => setModalOpen(false)} />
      )}
    <div className="inbox-ai-card">
      <div className="inbox-ai-card-head">
        <span className="inbox-ai-card-title">
          <Sparkles size={13} className="inbox-ai-card-spark" aria-hidden />
          AI Summary
        </span>
        <span className="inbox-ai-card-meta">
          {loading ? 'Generating…' : <GeneratedAgo at={item?.generatedAt ?? null} />}
        </span>
        <button
          type="button"
          className="inbox-ai-card-expand"
          onClick={() => setModalOpen(true)}
          title="Open detailed summary"
          aria-label="Open detailed summary"
        >
          <Maximize2 size={12} />
        </button>
        <button
          type="button"
          className={`inbox-ai-card-refresh ${loading ? 'spinning' : ''}`}
          onClick={onRefresh}
          disabled={loading}
          title="Regenerate summary"
          aria-label="Regenerate summary"
        >
          <RefreshCw size={12} />
        </button>
      </div>

      {digest ? (
        <div className="inbox-ai-card-body">
          {digest.headline && <p className="inbox-ai-headline">{digest.headline}</p>}
          {digest.done.length > 0 && (
            <ul className="inbox-ai-list inbox-ai-done">
              {digest.done.map((line, i) => (
                <li key={`d${i}`}>
                  <CheckCircle2 size={13} className="inbox-ai-bullet-icon done" aria-hidden />
                  <span>{line}</span>
                </li>
              ))}
            </ul>
          )}
          {digest.attention.length > 0 && (
            <ul className="inbox-ai-list inbox-ai-attention">
              {digest.attention.map((line, i) => (
                <li key={`a${i}`}>
                  <AlertCircle size={13} className="inbox-ai-bullet-icon attention" aria-hidden />
                  <span>{line}</span>
                </li>
              ))}
            </ul>
          )}
        </div>
      ) : loading ? (
        <div className="inbox-ai-card-body inbox-ai-card-skeleton" aria-hidden>
          <div className="inbox-ai-skel-line" />
          <div className="inbox-ai-skel-line short" />
          <div className="inbox-ai-skel-line" />
        </div>
      ) : (
        <div className="inbox-ai-card-body inbox-ai-card-fallback">
          {error === 'failed'
            ? 'Couldn’t generate a summary — click ↻ to retry.'
            : 'No summary yet.'}
        </div>
      )}
    </div>
    </>
  );
}

/** "Generated Xm ago" relative label; coarse minutes/hours like the inbox rows. */
function GeneratedAgo({ at }: { at: number | null }) {
  if (at === null) return <>Not generated yet</>;
  const diff = Math.max(0, Date.now() - at);
  let rel: string;
  if (diff < 60_000) return <>Generated just now</>;
  else if (diff < 3_600_000) rel = `${Math.floor(diff / 60_000)}m`;
  else if (diff < 86_400_000) rel = `${Math.floor(diff / 3_600_000)}h`;
  else rel = `${Math.floor(diff / 86_400_000)}d`;
  return <>Generated {rel} ago</>;
}
