#!/usr/bin/env node
/**
 * Apply the correct dialect's migration folder (generated by
 * `npm run db:generate` into `website/drizzle/{sqlite,pg}/`) to the database
 * selected by `DATABASE_URL` (see `lib/db/index.ts::resolveDialect`):
 *   - unset / `file:…` → `drizzle/sqlite/`
 *   - `postgres(ql)://…` → `drizzle/pg/`
 *
 * Idempotent: drizzle-orm's migrator tracks applied migrations in a
 * `__drizzle_migrations` table and skips ones already run, so re-invoking
 * this on an up-to-date database is a no-op.
 *
 * `package.json`'s `db:migrate` script invokes this file by path (Phase 0
 * wired it to `lib/db/migrate.mjs`) — filename/extension must match.
 */
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getDb } from './index.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
// website/drizzle/{sqlite,pg} — two levels up from lib/db/.
const DRIZZLE_ROOT = join(HERE, '..', '..', 'drizzle');

async function main() {
  const { dialect, db } = await getDb();
  const migrationsFolder = join(DRIZZLE_ROOT, dialect);

  if (dialect === 'pg') {
    const { migrate } = await import('drizzle-orm/node-postgres/migrator');
    await migrate(db, { migrationsFolder });
  } else {
    const { migrate } = await import('drizzle-orm/better-sqlite3/migrator');
    migrate(db, { migrationsFolder });
  }
  console.log(`db:migrate: applied ${dialect} migrations from ${migrationsFolder}`);
}

main().catch((err) => {
  console.error('db:migrate failed:', err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
