import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const browser=await chromium.launch({headless:true});
try {
const page=await browser.newPage({viewport:{width:1920,height:1200}});
const errors=[],external=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('request',request=>{if(/^https?:/.test(request.url()))external.push(request.url());});
await page.coverage.startJSCoverage({resetOnNavigation:false});
await page.goto(pathToFileURL(path.join(root,'index.html')).href);
// Every transition, both sides of the boundary, plus the typing and streaming states.
await page.evaluate(()=>{for(let t=0;t<=130;t+=.1)demo.seek(t);});
await page.evaluate(()=>demo.seek(DemoTimeline.toPresentation(55)));
assert.equal(await page.locator('.answer-option.selected').count(),1);
assert.match(await page.locator('.toolbar .status').innerText(),/Needs you/);
await page.locator('[data-cue="continue"]').click();
assert.match(await page.locator('.toolbar .status').innerText(),/Working/);
await page.evaluate(()=>demo.seek(DemoTimeline.toPresentation(98)));
assert.match(await page.locator('[data-cue="watch"]').innerText(),/Watching/);
await page.locator('[data-cue="work-with-agent"]').click();
assert.match(await page.locator('.draft').innerText(),/W-100042/);
assert.equal((await page.evaluate(()=>demo.state())).time,70);
await page.locator('[data-cue="send"]').click();
assert.equal((await page.evaluate(()=>demo.state())).time,73.5);
await page.locator('#chapter-select').selectOption('77.5');
await page.locator('[data-cue="new-plugin"]').click();
assert.equal((await page.evaluate(()=>demo.state())).time,80.5);
await page.locator('#explore').click();
assert.equal(await page.locator('[data-count]').innerText(),'0 of 3 complete');
await page.locator('[data-toggle="0"]').click();
assert.equal(await page.locator('[data-count]').innerText(),'1 of 3 complete');
await page.locator('[data-toggle="0"]').click();
assert.equal(await page.locator('[data-count]').innerText(),'0 of 3 complete');
await page.locator('#new-task').fill('   ');
await page.locator('#new-task').press('Enter');
assert.equal(await page.locator('.focus-task').count(),3);
await page.locator('#new-task').fill('Share <b>my</b> update');
await page.locator('#new-task').press('Enter');
assert.equal(await page.locator('.focus-task').count(),4);
assert.equal(await page.locator('.focus-task').last().locator('strong').innerText(),'Share <b>my</b> update');
assert.equal(await page.locator('.focus-task b').count(),0);
for(const title of ['Fifth task','Sixth task','Exceeds the demo limit']){await page.locator('#new-task').fill(title);await page.locator('#new-task').press('Enter');}
assert.equal(await page.locator('.focus-task').count(),6);
await page.evaluate(()=>demo.seek(DemoTimeline.toPresentation(175)));
await page.locator('[data-toggle="2"]').click();
assert.equal(await page.locator('[data-count]').innerText(),'3 of 4 complete');
await page.evaluate(()=>demo.seek(DemoTimeline.toPresentation(170)));
await page.locator('[data-cue="focus-add"]').click();
assert.equal((await page.evaluate(()=>demo.state())).exploring,true);
await page.locator('#restart').click();
await page.waitForTimeout(180);
assert.equal((await page.evaluate(()=>demo.state())).running,true);
await page.locator('#play').click();
assert.equal((await page.evaluate(()=>demo.state())).running,false);
await page.locator('#seek').fill('57.65');
await page.locator('#seek').dispatchEvent('input');
assert.equal((await page.evaluate(()=>demo.state())).time,57.65);
await page.locator('#sound').click();
await page.locator('#play').click();
await page.waitForTimeout(180);
assert.equal(await page.locator('#narration').evaluate(a=>a.paused),false);
await page.locator('#sound').click();
assert.equal(await page.locator('#narration').evaluate(a=>a.paused),true);
await page.evaluate(()=>{demo.seek(DemoTimeline.toPresentation(189.94));demo.play();});
await page.waitForTimeout(180);
assert.equal((await page.evaluate(()=>demo.state())).running,false);
await page.locator('#play').click();
await page.waitForTimeout(100);
assert.ok((await page.evaluate(()=>demo.state())).time<1);
await page.evaluate(()=>demo.pause());
await page.setViewportSize({width:1280,height:900});
await page.evaluate(()=>demo.seek(DemoTimeline.toPresentation(161)));
assert.ok(Math.abs((await page.locator('#stage').boundingBox()).width-1280)<1);
// Capture mode hides the player and keeps a precise video frame.
const playbackCoverage=await page.coverage.stopJSCoverage();
await page.coverage.startJSCoverage();
await page.goto(pathToFileURL(path.join(root,'index.html')).href+'?capture=1');
await page.evaluate(()=>demo.seek(DemoTimeline.toPresentation(66)));
assert.equal(await page.locator('.player').isVisible(),false);
const coverage=[...playbackCoverage,...await page.coverage.stopJSCoverage()].filter(e=>/\/(app|timeline|story-timeline)\.js$/.test(e.url));
const merged=new Map();
for(const entry of coverage){
  const flags=new Uint8Array(entry.source.length);
  const ranges=entry.functions.flatMap(f=>f.ranges).sort((a,b)=>(b.endOffset-b.startOffset)-(a.endOffset-a.startOffset));
  for(const range of ranges)flags.fill(range.count>0?1:0,range.startOffset,range.endOffset);
  const previous=merged.get(entry.url)||new Uint8Array(flags.length);
  flags.forEach((flag,i)=>{if(flag)previous[i]=1;});merged.set(entry.url,previous);
}
const totals=[...merged].map(([url,flags])=>({file:path.basename(url),bytes:flags.length,used:flags.reduce((sum,v)=>sum+v,0)}));
const covered=totals.reduce((n,e)=>n+e.used,0)/totals.reduce((n,e)=>n+e.bytes,0);
assert.ok(covered>=.8,`Expected >=80% browser JS coverage, got ${covered*100}%`);
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
const report={ok:true,browser:browser.version(),externalRequests:external.length,pageErrors:errors,jsCoveragePercent:+(covered*100).toFixed(2),coverage:totals,checks:['every timeline transition','question and resume','GUS ticket draft then send','plugin add/toggle/blank input/escaping/bound','play/pause/restart/seek/chapter jump','narration enable and pause','end of playback','responsive scale and capture mode']};
await writeFile(path.join(root,'render/verification.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
} finally { await browser.close(); }
